---
abstract: 'Lightweight class builder with DSL'
author:
  - tokuhirom
build_requires:
  Test::More: 0
distribution_type: module
generated_by: 'Module::Install version 0.77'
license: perl
meta-spec:
  url: http://module-build.sourceforge.net/META-spec-v1.4.html
  version: 1.4
name: Shika
no_index:
  directory:
    - inc
    - t
requires:
  MRO::Compat: 0
resources:
  license: http://dev.perl.org/licenses/
version: 0.01_01
